### ISSUE TITLE
How will SearchOcean be displayed?

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/searchocean-app#2]
Maybe load the content using <a href="https://isomorphic-git.org/">isomorphic-git</a>?

**Comment by JaydenDev** [comment]
Its loaded with a webview
unfortunately it shows a white screen.
Most of the app has already been made, just fix the white screen.

**Comment by hello-smile6** [comment]
> Its loaded with a webview unfortunately it shows a white screen. Most of the app has already been made, just fix the white screen.

Got it.

**Comment by hello-smile6** [comment]
> Its loaded with a webview unfortunately it shows a white screen. Most of the app has already been made, just fix the white screen.

#3
